### ISSUE TITLE
How to get a partial AST for a partial input?

### ISSUE THREAD

**Issue by jadetang** [mna/pigeon#154]
Hello, we are using this tool, it works well for our project.
Now I want to implement the autocomplete in the LSP where most of the time the input is incomplete.
Is it possible to get a partial AST? 
I read the error label and recovery document and examples, but I am not sure that can work for me, because I don't need to continue parsing in case something goes wrong.
Any suggestion is appreciated.

**Comment by breml** [comment]
Hi @jadetang 
Me personally, I have never tried to build a parser with pigeon, that works on partial AST. That being said, two ideas come to mind:

* As you have already mentioned, the error label and recovery are the features, that might be helpful for this scenario.
* Alternatively, you might want to create a grammar, that supports something like `<the_thing> / <maybe_the_thing>`, where `<maybe_the_thing>` is defined such, that it matches something, that could become `<the_thing>`, but is not yet complete (basically matching the prefix).
* Do some research, if there are papers about using PEG for partial AST, maybe you are lucky.

But since I have never done such a thing, I might not be of a lot of help.

**Comment by jadetang** [comment]
@breml 
thanks, I think the second approach sounds promising. I will try that.

**Comment by jadetang** [comment]
@breml sorry to bother you again.
I got an idea, but I am not sure if it works because I am not very familiar with the internal of the parser.
Assume my grammar is defined as 

`s<- expr1 exp2 expr3 %{errCondition}
