### ISSUE TITLE
How to pass in data into parser

### ISSUE THREAD

**Issue by felipellrocha** [mna/pigeon#61]
In `peg.js` I'm able to pass data into the parser via an `options` variable. Is there an example of how I could do the same here?

**Comment by breml** [comment]
@felipellrocha Thanks for your question. Have a look at the [GlobalStore](https://godoc.org/github.com/mna/pigeon/test/predicates#GlobalStore) function, which can be used to pass arbitrary data to the global store of the parser. See also the respective section in [godoc](https://godoc.org/github.com/mna/pigeon#hdr-Code_block) or [this test](https://github.com/mna/pigeon/blob/master/test/global_store/global_store_test.go#L31) as an example how to use it.

**Comment by felipellrocha** [comment]
This example confuses me a little bit... How do I pass multiple options? Also... Option is a function that returns other Options?

**Comment by breml** [comment]
@felipellrocha The function [Parse](https://godoc.org/github.com/mna/pigeon/test/predicates#Parse) (and its variants `ParseFile` and `ParseReader`) accept a variadic list of options as aguments. This means, that you can parse the above mentioned `GlobalStore` function multiple times to set multiple values in the global store.
The type `Option` is a function, which returns the previous setting as an option, which means, that the returned option function could be used to reset the previous state. this being said, this is not used here, because these option functions are not returned in [setOptions](https://github.com/mna/pigeon/blob/master/test/global_store/global_store.go#L597)).

In the end, what matters for you is, that you can use the `GlobalStore` function to initialize the global store with multiple values upon creation of the parser like this:

```
got, err := Parse("", []byte(test.input), GlobalStore("key1", value1), GlobalStore("key2", value2))
```
