### ISSUE TITLE
cloneState/restoreState reuses state if no keys have been set

### ISSUE THREAD

**Issue by d4l3k** [mna/pigeon#73]
This test fails since the same empty state is returned from cloneState multiple times.

```go
func TestState(t *testing.T) {
	var p parser
	p.emptyState = make(storeDict)
	p.cur.state = make(storeDict)
	p.restoreState(p.cloneState())
	c := &p.cur

	backup := p.cloneState()

	c.state["foo"] = true

	p.restoreState(backup)
	if len(p.cur.state) > 0 {
		t.Fatalf("leaking state! %#v", p.cur.state)
	}
}
```

**Comment by breml** [comment]
@d4l3k thanks for the issues and the pr. I am currently on vacation and I will have a look when I am back.

**Comment by d4l3k** [comment]
Do you know when that'll be? Hope you're having a good vacation!

**Comment by breml** [comment]
I am away for an other week.

**Comment by breml** [comment]
@d4l3k Now I am back from my vacation and I looked at this issue as well as your PR #74.
I understand the change you are proposing and also your test. Do you have an actual PEG grammar, that suffers from this particular problem? Do you mind to add a test case including such a PEG grammar, where to problem is shown when the generated parser is acutally used? I would prefer to have a test case, where the exposed API is used instead of directly call the private methods `cloneState` and `restoreState` directly.
Also I would prefer to have the formatting changes you performed to have in a separate commit.

**Comment by d4l3k** [comment]
I do have a PEG grammar that suffers from this problem which is how I found the bug. 

https://github.com/d4l3k/wikigopher/blob/master/wikitext/wikitext.peg

It's pretty large though and seemed easier to write a unit test than create a stripped down version of it.

Formatting changes happened automatically sorry. I have gofmt set to run every time I save a file.
