### ISSUE TITLE
No match found when it should match a later type

### ISSUE THREAD

**Issue by danielgtaylor** [mna/pigeon#77]
Hello! I have built a (relatively simple) parser to provide a [shorthand syntax that expands to JSON or YAML for command-line utilities](https://github.com/danielgtaylor/openapi-cli-generator/tree/master/shorthand) using Pigeon. Keep in mind I've never made a parser before! :smile:

The PEG file essentially takes key/value pairs and turns them into a list of AST-like nodes. The [value can consist of `Null / Bool / Float / Int / String`](https://github.com/danielgtaylor/openapi-cli-generator/blob/master/shorthand/shorthand.peg#L132) and it works great except for one strange case that I have discovered and noted in danielgtaylor/openapi-cli-generator#13:

```sh
# Works fine
$ j foo: bar.baz.blah
{
  "foo": "bar.baz.blah"
}

# Works fine
$ j foo: 1.2
{
  "foo": 1.2
}

# Fails!
$ j foo: 1.2.3
panic: stdin:1:9 (8): no match found, expected: ",", [ \t\r\n], [0-9] or EOF

goroutine 1 [running]:
main.main.func1(0xc0000c8c80, 0xc00009a400, 0x2, 0x2)
	/Users/dan/Projects/src/github.com/danielgtaylor/openapi-cli-generator/j/main.go:26 +0x2ec
github.com/spf13/cobra.(*Command).execute(0xc0000c8c80, 0xc000092190, 0x2, 0x2, 0xc0000c8c80, 0xc000092190)
	/Users/dan/Projects/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c8c80, 0x122527a, 0x20, 0xc000090a80)
	/Users/dan/Projects/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0000c8c80, 0x121e86b, 0x6)
	/Users/dan/Projects/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
	/Users/dan/Projects/src/github.com/danielgtaylor/openapi-cli-generator/j/main.go:53 +0x2f2
```

What I don't understand is how this is happening. 

Float definition: `Float ← [0-9]+ '.' [0-9]+`
Int definition: `Int ← [0-9]+`
String definition: `String ← [^,}]*`

Based on the grammar I would think that the float begins to match, then fails at the second `.`. The int will match until the first `.`, and then it should fall back to a normal string. Any help you can give would be greatly appreciated.

**Comment by mna** [comment]
Hello Daniel,

The problem is that `Float` *does* match, so your `foo: 1.2.3` input is parsed as `"foo": 1.2` and then it expects a comma (i.e. if there's another field-value pair coming after), whitespace, more digits or EOF, but finds the second dot. A similar issue would happen if you had `Int` before `Float` in your `Value` rule, it would parse this as an `Int` and would fail at the *first* dot. The `/` operator is ordered and stops at the first successful match.

One way to force it to parse a value the way you describe would be to check with a lookahead that it is followed by a value separator (i.e. "," or I guess newline or EOF, not sure about how you want your format).

Have fun!
Martin

**Comment by danielgtaylor** [comment]
Thanks, this has been super useful! I wound up using the [lookahead](https://godoc.org/github.com/mna/pigeon#hdr-And_and_not_expressions) like you suggested:

```peg
ValueEnd ← _ [,}\]] / EOF

Float ← [0-9]+ '.' [0-9]+ &ValueEnd {
  return strconv.ParseFloat(string(c.text), 64)
}

Int ← [0-9]+ &ValueEnd {
  return strconv.Atoi(string(c.text))
}
```

I wrote a few new tests and everything is now passing. :+1:
