### ISSUE TITLE
Accessing filename during parsing

### ISSUE THREAD

**Issue by tsandall** [mna/pigeon#8]
I have a use case where I want to propagate the filename into the AST nodes generated by my parser.

Is there a way to access the filename during parsing? It seems it would be easy enough to put the filename on the `current` struct. Any suggestions?

Thanks!

**Comment by PuerkitoBio** [comment]
Hello Torin,

You should be able to do this without changing pigeon, for example if your top-level AST node returned from the call to `Parse*` has a `Filename` field, you can set it after the call.

Martin

**Comment by tsandall** [comment]
This can definitely be done with a post-processing step. However, in this case, it's not only the top-level AST node that has file/location information on it. All of the AST nodes have this. It seems it would be cleaner to set this information during parsing as opposed to walking the AST afterwards to do the same.

Giving `current` a member to store context seems it would aid this use case and potentially others.

**Comment by PuerkitoBio** [comment]
I'm not sure I understand why you'd want to store the filename on each node in the tree? Given a top-level node returned from the parser, all children's positions are necessarily from the same input file, so there's no need to walk the tree after parsing?

**Comment by tsandall** [comment]
The AST nodes include location info for debugging purposes (e.g., line, column, etc.). Given an arbitrary AST node, it's not always possible to get the top-level node, so instead, the filename is stored with the location info.

**Comment by PuerkitoBio** [comment]
You always need more information than an arbitrary node when walking an AST - e.g. if you're processing a variable declaration node, you need state from the rest of the tree to know if you are in a function, in a top-level package, etc. You don't duplicate all that information on each child node, you manage that state as you walk the tree. The filename is no different IMO.

That being said, I'm not closed to the idea, just trying to see if that's the best way or valuable enough, it's been a long time since I worked on pigeon and I need to get familiar with it again.

**Comment by breml** [comment]
@tsandall I don't know, if this issue is still relevant for you. But if this is the case, I would appreciate, if you could have a look at #23, if this would solve your problem of accessing the filename during parsing. In your case, you could use the function `GlobalState` as `Option` for the parser to place the filename in the global store (see https://github.com/mna/pigeon/pull/23/files#diff-3936a49b4c04f9aed5d829709d361384R31). Any feedback is appreciated.

**Comment by tsandall** [comment]
@breml It definitely looks like this would work for this use case. That being said, I ended up adding a post-processing step so this issue can be closed.
