### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [mna/pigeon#89]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

CCing @mna 

Cheers,
Yevgeny

**Comment by breml** [comment]
@yevgenypats Thanks for your suggestion. It sounds interesting to me and I have thought about this in the past as well. The _problem_ I see is, that pigeon is a parser generator, so you do not know in advance, what the generated parsers will be used for. So I am not sure, how you would approach that.

That being said, I am open for this and I would appreciate if you could provide a draft for such a PR. Maybe it is easier to discuss the further steps based on real code.

**Comment by breml** [comment]
@yevgenypats are you still looking into this?

**Comment by yevgenypats** [comment]
@breml sorry for dropping the ball on this. looks like it slipped from my excel of things to do. I gave it a quick look now and essentially the first thing would be to choose the first function that would make sense to fuzz. is `ParseReader` a good candidate? or maybe you can suggest other function that get bytes or string array. we are not necessary need to know in advance what would be the outcome of ParseReader with random data but even if we can some kind of null-deref or a crash this will be good outcome of our bug-hunting.

**Comment by breml** [comment]
@yevgenypats Yes, `ParseReader` would be a good candidate. The question is, which parser we want to use for the tests, because due to the nature of `pigeon` being a parser generator, not all parsers use the full set of functionalities. Maybe we start with a simple case like `examples/json`, which has the advantage, that the result can easily be verified by using `encoding/json` with the same input.

`pigeon` offers some options to optimize the generated parser. So to start, I suggest to fuzz with the normal (not optimized) parser. When can then still move forward and also test the optimized variants later.

Additionally, a clear problem that I can see is, that also due to the nature of the parser it is pretty easy to overflow the stack (see `test/linear/linear_test.go` for a test case, where 1 MB of input is enough to overflow the stack while parsing some base64 encoded input). I guess, that fuzzing will pretty soon provide similar cases for an already known problem.

**Comment by yevgenypats** [comment]
ccing @bookmoons who will take the lead on that.

**Comment by bookmoons** [comment]
Hi @breml. Will be digging into this soon.

I remember pest has some fuzzing. They're a similar project, they handle PEG grammars. I'm going to have a look at their approach. Maybe it can be duplicated.

https://github.com/pest-parser/pest/blob/master/FUZZING.md

**Comment by bookmoons** [comment]
And thanks for the really good suggestions here. Will apply them to the fuzzers.

**Comment by bookmoons** [comment]
It seems like pest is fuzzing the generator and couple generated parsers, JSON and TOML. One target each.

**Comment by bookmoons** [comment]
There's a functional fuzz target for the JSON parser. It validates against the `encoding/json` result.

https://github.com/mna/pigeon/compare/f3db42a662eded7550fc7cd11605d05311dfa30f...bookmoons:debb9439b57c77ebbe9c128ec6efa6ca23f0b311

It runs with:
```go
cd examples/json
go-fuzz-build
go-fuzz
```

In a local run it found that pigeon parses the input `0`, but `encoding/json` returns an error.

**Comment by bookmoons** [comment]
If you'd like to get the other parsers fuzzed I can run through them. Some guidance about how to access them as a library would be helpful. go-fuzz can't get at a `main` package. I see in the docs there's some setup needed, but I'm not sure which pieces exactly.

**Comment by breml** [comment]
@bookmoons Thanks for your first results. In regards to the error your code found, I think the problem is not in the parser or in `encoding/json` but in your fuzzing code. [Line 13](https://github.com/mna/pigeon/compare/f3db42a662eded7550fc7cd11605d05311dfa30f...bookmoons:debb9439b57c77ebbe9c128ec6efa6ca23f0b311#diff-bac6a9ef1ac52e565ed5a26fab2a7b0cR13) needs to read `expectedErr := json.Unmarshal(fuzz, &expected)` as the target for `json.Unmarshal` needs to be a pointer.

**Comment by breml** [comment]
With this change in place, go-fuzz found two other crashers `00` and UTF-8 invalid rune. I will have a look on these.

**Comment by breml** [comment]
@bookmoons I looked into the three issues mentioned above and detected by go-fuzz:

* input `00` is a bug in the parser, fixed in #92 
* the second problem with the invalid UTF-8 rune (`\xf0`) is related to the UTF-8 encoding, where the pigeon based parser and the json unmarshal from the stdlib do not behave the same way so it does not make to compare them directly. To mitigate this, to following code can be added in the `json_fuzz.go` (after [Line 15](https://github.com/mna/pigeon/compare/f3db42a662eded7550fc7cd11605d05311dfa30f...bookmoons:debb9439b57c77ebbe9c128ec6efa6ca23f0b311#diff-bac6a9ef1ac52e565ed5a26fab2a7b0cR15):

```Go
if strings.Contains(err.Error(), "invalid encoding") {
    return 0
}
```

* the third issue with the input `\udb00\udf00`  is related to the fact, that the parser from stdlib does understand UTF-16 whereas the pigeon based does not. So again, it does not make sense to directly compare the output for these two cases. Unfortunately, this case can not be easily mitigated.

**Comment by bookmoons** [comment]
Nice, thanks a lot @breml. Made the updates.

https://github.com/mna/pigeon/compare/d6c23edb9fec1174b5fcc078bc63271930d47473...bookmoons:6c45dc536aaa7d992eafa5b796595800bcf677d2

For the invalid encoding error I returned the ignore signal `-1`, to stop it exploring that branch any further.

I wonder if it makes sense to have 2 targets here. The current one that validates against the stdlib result. And another that just runs pigeon decoding and detects crashes. That way it can explore the branches where the stdlib varies and catch bugs in those areas.

**Comment by breml** [comment]
@bookmoons Yes, this sounds reasonable. The second target, which just runs pigeon decoding and detects crashes, could be quite generic, such that it can be used with any parser, that has been generated with pigeon. As a final step (after we have gained some experience), we could even consider to generate such a generic fuzzing target with pigeon automatically (I think I would add a flag to pigeon for this case).

For the integration of the fuzzing into the pigeon repository I am wondering, which files are included into the git repository and which files are excluded via `.gitignore`. Can you give some recommendations on this as well?

CC: @yevgenypats

**Comment by breml** [comment]
@bookmoons In regards to the updated fuzzer, the situations, where it detects differences because of UTF-16 encoded runes is still open and will still lead to crashes, which are kind of false positives. Do you have a suggestion for this case as well?

**Comment by breml** [comment]
@bookmoons And one more idea, because pigeon supports different levels of optimizations (parser optimization, grammar optimization), one thing we could do is to compare the results of the differently optimized parser against each other, because if the fuzzer finds a difference there, it is most certainly a bug.

**Comment by breml** [comment]
The fuzzer also found the already known bug, that the pigeon based json decoder fails on escaped forward slashes in string values (see: https://github.com/mna/pigeon/blob/f838cbe38d8094542d814c3e1f2b8d462a4dfe01/examples/json/json.peg#L65). I created a fix and a test case for this in #93 .

**Comment by bookmoons** [comment]
Added a simple JSON fuzzer that just runs the parser on fuzz. Panics will signal bugs.

https://github.com/mna/pigeon/compare/d6c23edb9fec1174b5fcc078bc63271930d47473...bookmoons:8bc3f5c099dd55dc33e153bedae1c38cf53f12be

You can target the build with `-func`.

```shell
go-fuzz-build -func FuzzSimple
go-fuzz
```

```shell
go-fuzz-build -func FuzzStandard
go-fuzz
```

>As a final step (after we have gained some experience), we could even consider to generate such a generic fuzzing target with pigeon automatically (I think I would add a flag to pigeon for this case).

This would be a really nice setup.

**Comment by bookmoons** [comment]
Here's an example of a recent integration:
https://github.com/tsenart/vegeta/pull/432

Typical Fuzzit setup uses a `fuzzit.sh` script and some lines in the Travis config file. There's the script for vegeta:
https://github.com/bookmoons/vegeta/blob/13242e1d4e37fefc2776ce7bc5dced26a1191656/fuzzit.sh

The setup has 2 stages in CI, fuzz regression and the main fuzz stage. Fuzz regression pulls past crashes and does a quick run in CI to catch regressions. The main fuzz stage submits to Fuzzit to start a longer run and ends the build as soon as it's the queue. Then Fuzzit emails if it finds bugs.

The script does a clean install of everything on every build, including rebuilding the fuzzer. Then the fuzzer binary is submitted to Fuzzit and runs on the Fuzzit servers. So all the working data is isolated to the Fuzzit environment.

Typically I haven't been using gitignore. If you'd like to do local runs of the fuzzer it wouldn't hurt to ignore that working data it generates. I think it would look like this.

```gitignore
corpus/
crashers/
suppressions/
*-fuzz.zip
```

**Comment by bookmoons** [comment]
>differences because of UTF-16 encoded runes is still open and will still lead to crashes, which are kind of false positives. Do you have a suggestion for this case as well?

I wonder if it's possible to detect a UTF-16 byte string and just exclude them from fuzzing. What do you think? Seems like they're using the `unicode/utf16` package. Maybe their detection can be duplicated.

https://golang.org/src/encoding/json/decode.go

**Comment by bookmoons** [comment]
>one thing we could do is to compare the results of the differently optimized parser against each other, because if the fuzzer finds a difference there, it is most certainly a bug.

This is a really good idea. go-fuzz recommends doing this to find consistency bugs. I vote yes.

In another integration I generated a parser at fuzz time in CI, in that fuzzit script. Maybe the same thing could be done here. Fuzzing of a parser could look like:
* Generate all optimized/unoptimized variants.
* Simple fuzz of each individually.
* Single consistency fuzz of all.

**Comment by bookmoons** [comment]
Tried to add some rough exclusion of the UTF-16 surrogates in https://github.com/mna/pigeon/compare/d6c23edb9fec1174b5fcc078bc63271930d47473...bookmoons:78b0c6311f0ef0ac8d60d6c12c93f0f6566adb1c.

I see it's tough to do because they only happen in JSON strings. This catches them everywhere. Maybe it's enough for a start.

There must be a regex that would catch them only in strings, but I'm not sure how difficult that would be.

**Comment by bookmoons** [comment]
https://github.com/mna/pigeon/compare/d6c23edb9fec1174b5fcc078bc63271930d47473...bookmoons:7a867c4fe1a3b19b394e85c46df585d40e6c0855 tries your idea of fuzzing optimized parsers. All the fuzzers seem to be run. It seems like a good setup.

```shell
go-fuzz-build -func FuzzUnoptimized && go-fuzz
go-fuzz-build -func FuzzOptimizedParser && go-fuzz
go-fuzz-build -func FuzzOptimizedGrammar && go-fuzz
go-fuzz-build -func FuzzInternalConsistency && go-fuzz
go-fuzz-build -func FuzzExternalConsistency && go-fuzz
```

**Comment by breml** [comment]
@bookmoons thanks for the update. This looks promising and I will have a detailed look at this. I have some pretty packed days in front of me and afterwards I am off for vacation. So unfortunately, this needs to wait.
You thing, that I already spotted is the `regex.Match` for the UTF-16. I suggest to create a global variable (actually it is more like a constant) for the regex matcher, which is better in regards to performance, because this regex is executed for each input to the parser during the fuzzing. So my suggestion would be like this:

```Go
var re = regexp.MustCompile(`\\u[dD][89a-f-AF][0-9a-fA-F]{2}`)

func excludeFuzz(fuzz []byte) bool {
	return re.Match(fuzz)
}
```

And with that, the function excludeFuzz is maybe no longer necessary an can be inlined in the existing code.

**Comment by bookmoons** [comment]
https://github.com/mna/pigeon/compare/d6c23edb9fec1174b5fcc078bc63271930d47473...bookmoons:fe0e983d2759e5613d77c8495f079ac1cd6f4dff updates that.
