### ISSUE TITLE
Latest pigeon fails to parse examples/indentation/indentation.peg

### ISSUE THREAD

**Issue by philandstuff** [mna/pigeon#91]
I ran:

```
go get -u github.com/mna/pigeon
curl -s https://raw.githubusercontent.com/mna/pigeon/master/examples/indentation/indentation.peg | pigeon
```

and I got the output:

```
parse error(s):
 stdin:1:1 (0): no match found
```

This is surprising, because I expect the examples provided with pigeon to parse correctly with pigeon.

(Context: I was trying to use the `#{}` state-change block syntax, and I couldn't get it to work, so I thought I'd look at one of the examples that use it; only the example didn't work either.  This may or may not be related to the failure to parse :man_shrugging:)

**Comment by breml** [comment]
@philandstuff Just to understand your test setup better, did you have an older version of the pigeon in the `$GOPATH` before you ran `go get -u github.com/mna/pigeon` (I am asking because you are providing the `-u` flag)?

Can you test, if you run `make clean && make`. This gives you the latest version of `pigeon` in the `bin/` directory.

**Comment by philandstuff** [comment]
Urgh, I got bitten by go modules.  Running the `go get -u ...` command from outside a module directory worked better, and now it parses as expected.

Sorry for the noise.

**Comment by flowchartsman** [comment]
This isn't exactly noise. It's the result of Go modules' version selection interacting with a v1 release that does not build example rules. Anyone running into this issue is encouraged to `go get github.com/mna/pigeon@18953b2` (or whatever the latest commit is) from inside of their module until a new release is cut.
